// src/components/sections/NotificationsSection.tsx
/* ============================================================================
   通知中心 —— 运营侧操作类通知列表，支持状态/级别筛选、标记已读、定位跳转。
   忠实移植自 NotificationsSection.vue，视觉换用 Soft 设计系统。
   ============================================================================ */
import { useApp } from "../../runtime/AppContext";
import { Button, Pill, Select, Empty } from "../primitives";

export default function NotificationsSection() {
  const ctx = useApp();

  const statusOptions = [
    { label: "未读", value: "unread" },
    { label: "全部状态", value: "all" },
    { label: "已读", value: "read" },
  ];

  const severityOptions = [
    { label: "全部级别", value: "all" },
    { label: "严重", value: "critical" },
    { label: "提醒", value: "warning" },
    { label: "信息", value: "info" },
  ];

  const rows = ctx.notifications.value;

  return (
    <section className="content-stack">
      <div className="panel">
        {/* 面板头：标题 + 操作区 */}
        <div className="panel-title">
          <div>
            <h2>通知中心</h2>
            <p>集中展示铺货失败、采购映射缺失、履约发货失败、售后待处理和店铺同步异常。</p>
          </div>
          <div className="button-group">
            <Select
              value={ctx.notificationStatusFilter.value}
              onChange={(v) => {
                ctx.notificationStatusFilter.value = v;
                ctx.refreshNotifications();
              }}
              options={statusOptions}
              width={110}
            />
            <Select
              value={ctx.notificationSeverityFilter.value}
              onChange={(v) => {
                ctx.notificationSeverityFilter.value = v;
                ctx.refreshNotifications();
              }}
              options={severityOptions}
              width={110}
            />
            <Button icon="refresh" onClick={() => ctx.refreshNotifications()}>
              刷新
            </Button>
            <Button icon="check" onClick={() => ctx.markAllNotificationsRead()}>
              全部已读
            </Button>
          </div>
        </div>

        {/* KPI strip */}
        <dl className="status-list compact">
          <div>
            <dt>未读通知</dt>
            <dd>{ctx.unreadNotificationCount.value}</dd>
          </div>
          <div>
            <dt>严重未读</dt>
            <dd>{ctx.criticalNotificationCount.value}</dd>
          </div>
          <div>
            <dt>当前筛选</dt>
            <dd>{ctx.notificationTotal.value}</dd>
          </div>
        </dl>

        {/* 通知表格 */}
        <div className="tbl-wrap">
          <table className="tbl dense-table">
            <thead>
              <tr>
                <th style={{ width: 90 }}>级别</th>
                <th style={{ width: 90 }}>状态</th>
                <th style={{ minWidth: 120 }}>来源</th>
                <th style={{ minWidth: 130 }}>店铺</th>
                <th style={{ minWidth: 380 }}>通知</th>
                <th style={{ minWidth: 190 }}>更新时间</th>
                <th style={{ width: 170 }}>操作</th>
              </tr>
            </thead>
            <tbody>
              {rows.length === 0 ? (
                <tr>
                  <td colSpan={7}>
                    <Empty>暂无数据</Empty>
                  </td>
                </tr>
              ) : (
                rows.map((row) => (
                  <tr key={row.id}>
                    {/* 级别 */}
                    <td>
                      <Pill tone={ctx.notificationSeverityType(row.severity)}>
                        {ctx.notificationSeverityLabel(row.severity)}
                      </Pill>
                    </td>
                    {/* 状态 */}
                    <td>
                      <Pill tone={ctx.statusType(row.status)}>
                        {row.status === "unread" ? "未读" : "已读"}
                      </Pill>
                    </td>
                    {/* 来源 */}
                    <td>{ctx.notificationSourceLabel(row.source_type)}</td>
                    {/* 店铺 */}
                    <td>{row.shop_name || row.shop_id || "-"}</td>
                    {/* 通知 */}
                    <td>
                      <div className="cell-main">
                        <strong>{row.title}</strong>
                        <span className="subtext">{row.body}</span>
                      </div>
                    </td>
                    {/* 更新时间 */}
                    <td>{ctx.formatDateTime(row.updated_at)}</td>
                    {/* 操作 */}
                    <td>
                      <div className="row-actions">
                        <Button
                          size="sm"
                          icon="bell"
                          variant="ghost"
                          onClick={() => ctx.openNotification(row)}
                        >
                          定位
                        </Button>
                        {row.status !== "read" && (
                          <Button
                            size="sm"
                            icon="check"
                            variant="ghost"
                            onClick={() => ctx.markNotificationRead(row)}
                          >
                            已读
                          </Button>
                        )}
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </section>
  );
}

// src/components/sections/NotificationsSection.vue
<script setup lang="ts">
import type { WxXdAppContext } from "../../composables/useWxXdApp";

const props = defineProps<{ ctx: WxXdAppContext }>();
const {
  Bell,
  CircleCheck,
  criticalNotificationCount,
  formatDateTime,
  markAllNotificationsRead,
  markNotificationRead,
  notifications,
  notificationSeverityFilter,
  notificationSeverityLabel,
  notificationSeverityType,
  notificationSourceLabel,
  notificationStatusFilter,
  notificationTotal,
  openNotification,
  Refresh,
  refreshNotifications,
  statusType,
  unreadNotificationCount,
} = props.ctx;
</script>

<template>
      <section class="content-stack">
        <div class="panel">
          <div class="panel-title">
            <div>
              <h2>通知中心</h2>
              <p>集中展示铺货失败、采购映射缺失、履约发货失败、售后待处理和店铺同步异常。</p>
            </div>
            <div class="button-group">
              <el-select
                v-model="notificationStatusFilter"
                class="status-filter"
                @change="refreshNotifications"
              >
                <el-option value="unread" label="未读" />
                <el-option value="all" label="全部状态" />
                <el-option value="read" label="已读" />
              </el-select>
              <el-select
                v-model="notificationSeverityFilter"
                class="status-filter"
                @change="refreshNotifications"
              >
                <el-option value="all" label="全部级别" />
                <el-option value="critical" label="严重" />
                <el-option value="warning" label="提醒" />
                <el-option value="info" label="信息" />
              </el-select>
              <el-button :icon="Refresh" @click="refreshNotifications">刷新</el-button>
              <el-button :icon="CircleCheck" @click="markAllNotificationsRead">全部已读</el-button>
            </div>
          </div>

          <dl class="status-list compact">
            <div>
              <dt>未读通知</dt>
              <dd>{{ unreadNotificationCount }}</dd>
            </div>
            <div>
              <dt>严重未读</dt>
              <dd>{{ criticalNotificationCount }}</dd>
            </div>
            <div>
              <dt>当前筛选</dt>
              <dd>{{ notificationTotal }}</dd>
            </div>
          </dl>

          <el-table :data="notifications" class="dense-table">
            <el-table-column label="级别" width="90">
              <template #default="{ row }">
                <el-tag :type="notificationSeverityType(row.severity)">
                  {{ notificationSeverityLabel(row.severity) }}
                </el-tag>
              </template>
            </el-table-column>
            <el-table-column label="状态" width="90">
              <template #default="{ row }">
                <el-tag :type="statusType(row.status)">{{ row.status === "unread" ? "未读" : "已读" }}</el-tag>
              </template>
            </el-table-column>
            <el-table-column label="来源" min-width="120">
              <template #default="{ row }">
                {{ notificationSourceLabel(row.source_type) }}
              </template>
            </el-table-column>
            <el-table-column label="店铺" min-width="130">
              <template #default="{ row }">
                {{ row.shop_name || row.shop_id || "-" }}
              </template>
            </el-table-column>
            <el-table-column label="通知" min-width="380" show-overflow-tooltip>
              <template #default="{ row }">
                <strong class="notification-title">{{ row.title }}</strong>
                <span class="notification-body">{{ row.body }}</span>
              </template>
            </el-table-column>
            <el-table-column label="更新时间" min-width="190">
              <template #default="{ row }">{{ formatDateTime(row.updated_at) }}</template>
            </el-table-column>
            <el-table-column label="操作" width="170">
              <template #default="{ row }">
                <el-button size="small" :icon="Bell" @click="openNotification(row)">定位</el-button>
                <el-button
                  v-if="row.status !== 'read'"
                  size="small"
                  :icon="CircleCheck"
                  @click="markNotificationRead(row)"
                >
                  已读
                </el-button>
              </template>
            </el-table-column>
          </el-table>
        </div>
      </section>
</template>
