// src/components/sections/OperationsAnalyticsSection.tsx
/* 经营分析（analytics）—— 二级 Tab 壳：动销分析 / 库存风控 / 利润核算 */
import { useState } from "react";
import { useApp } from "../../runtime/AppContext";
import SalesSection from "./SalesSection";
import InventorySection from "./InventorySection";
import ProfitSection from "./ProfitSection";

const TABS = [
  { key: "sales", label: "动销分析" },
  { key: "inventory", label: "库存风控" },
  { key: "profit", label: "利润核算" },
];

export default function OperationsAnalyticsSection() {
  const ctx = useApp();
  const [tab, setTab] = useState("sales");
  return (
    <>
      <div className="pad" style={{ paddingBottom: 0 }}>
        <div className="wrap-wide">
          <div className="tabs" style={{ marginBottom: 0 }}>
            {TABS.map((t) => (
              <button
                key={t.key}
                className={`tab ${tab === t.key ? "on" : ""}`}
                onClick={() => setTab(t.key)}
              >
                {t.label}
              </button>
            ))}
            <button
              className="btn-link"
              style={{ marginLeft: "auto", alignSelf: "center" }}
              onClick={() => ctx.refreshAll()}
            >
              刷新全部
            </button>
          </div>
        </div>
      </div>
      {tab === "sales" && <SalesSection />}
      {tab === "inventory" && <InventorySection />}
      {tab === "profit" && <ProfitSection />}
    </>
  );
}

// src/components/sections/OperationsAnalyticsSection.vue
<script setup lang="ts">
import { ref } from "vue";
import type { WxXdAppContext } from "../../composables/useWxXdApp";
import SalesSection from "./SalesSection.vue";
import InventorySection from "./InventorySection.vue";
import ProfitSection from "./ProfitSection.vue";

const props = defineProps<{ ctx: WxXdAppContext }>();
const activeTab = ref("sales");
</script>

<template>
  <section class="content-stack">
    <div class="ops-page-head">
      <div>
        <p class="eyebrow">经营分析</p>
        <h2>用真实订单、成本、库存和售后判断下一步动作</h2>
        <p>这里只做合规经营判断：继续铺货、调价、补货、观察或下架。</p>
      </div>
      <el-button :icon="props.ctx.Refresh" @click="props.ctx.refreshAll">刷新</el-button>
    </div>

    <el-tabs v-model="activeTab" class="section-tabs">
      <el-tab-pane label="动销分析" name="sales">
        <SalesSection :ctx="props.ctx" />
      </el-tab-pane>
      <el-tab-pane label="库存风控" name="inventory">
        <InventorySection :ctx="props.ctx" />
      </el-tab-pane>
      <el-tab-pane label="利润核算" name="profit">
        <ProfitSection :ctx="props.ctx" />
      </el-tab-pane>
    </el-tabs>
  </section>
</template>
