// src/components/sections/ShopsSection.tsx
/* ============================================================================
   店铺与密钥管理 —— Soft 设计移植
   功能：(1) 店铺组管理，(2) 接入新店铺，(3) 已接入店铺总览 + 逐店操作
   ============================================================================ */
import { useApp } from "../../runtime/AppContext";
import { Button, Pill, Select } from "../primitives";

export default function ShopsSection() {
  const ctx = useApp();

  const groups = ctx.groups.value;
  const shops = ctx.shops.value;

  return (
    <section className="stack">
      {/* Panel 1 — 店铺组 */}
      <div className="panel">
        <div className="ph">
          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <h3>店铺组</h3>
            <Pill tone="info">{groups.length} 组</Pill>
          </div>
        </div>

        {/* 新建店铺组 inline 表单 */}
        <div className="toolbar" style={{ marginBottom: 12 }}>
          <input
            className="inp"
            value={ctx.groupForm.name}
            onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
              ctx.groupForm.name = e.target.value;
            }}
            placeholder="例如：默认铺货组"
            style={{ flex: 1, maxWidth: 320 }}
          />
          <Button variant="accent" icon="plus" onClick={() => ctx.createGroup()}>
            新建店铺组
          </Button>
        </div>

        {/* 店铺组表格 */}
        <div className="tbl-wrap">
          <table className="tbl">
            <thead>
              <tr>
                <th>店铺组</th>
                <th style={{ width: 100 }}>店铺数</th>
                <th style={{ width: 120 }}>状态</th>
                <th style={{ minWidth: 220 }}>ID</th>
              </tr>
            </thead>
            <tbody>
              {groups.length === 0 ? (
                <tr>
                  <td colSpan={4}>
                    <div className="empty">暂无数据</div>
                  </td>
                </tr>
              ) : (
                groups.map((row) => (
                  <tr key={row.id}>
                    <td>{row.name}</td>
                    <td>{row.shop_count}</td>
                    <td>
                      <Pill tone={ctx.statusType(row.status)}>{row.status}</Pill>
                    </td>
                    <td className="mono">{row.id}</td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Panel 2 — 接入店铺 */}
      <div className="panel">
        <div className="ph">
          <div>
            <h3>接入店铺</h3>
            <p>保存时 app_secret 只发送到 Tauri 后端加密入库，前端不展示、不回填。</p>
          </div>
        </div>

        <div className="form-grid cols-3" style={{ marginBottom: 12 }}>
          <input
            className="inp"
            value={ctx.shopForm.name}
            onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
              ctx.shopForm.name = e.target.value;
            }}
            placeholder="店铺名称"
          />
          <input
            className="inp"
            value={ctx.shopForm.appid}
            onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
              ctx.shopForm.appid = e.target.value;
            }}
            placeholder="微信小店 appid"
          />
          <input
            className="inp"
            type="password"
            value={ctx.shopForm.app_secret}
            onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
              ctx.shopForm.app_secret = e.target.value;
            }}
            placeholder="微信小店 app_secret"
            autoComplete="new-password"
          />
          <Select
            value={ctx.shopForm.group_id}
            onChange={(v: string) => {
              ctx.shopForm.group_id = v;
            }}
            options={ctx.selectedGroupOptions.value}
            placeholder="选择店铺组"
          />
          <div className="form-actions" style={{ gridColumn: "span 3" }}>
            <Button variant="accent" icon="plus" onClick={() => ctx.createShop()}>
              保存店铺
            </Button>
          </div>
        </div>
      </div>

      {/* Panel 3 — 店铺接入状态 */}
      <div className="panel">
        <div className="ph">
          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <h3>店铺接入状态</h3>
            <Pill tone="info">{shops.length} 店</Pill>
          </div>
        </div>

        <div className="tbl-wrap">
          <table className="tbl">
            <thead>
              <tr>
                <th style={{ minWidth: 150 }}>店铺</th>
                <th style={{ minWidth: 170 }}>appid</th>
                <th style={{ minWidth: 130 }}>店铺组</th>
                <th style={{ minWidth: 170 }}>微信资料</th>
                <th style={{ width: 130 }}>状态</th>
                <th style={{ width: 100 }}>密钥</th>
                <th style={{ minWidth: 190 }}>token 到期</th>
                <th style={{ width: 110 }}>接口额度</th>
                <th style={{ width: 250 }}>操作</th>
              </tr>
            </thead>
            <tbody>
              {shops.length === 0 ? (
                <tr>
                  <td colSpan={9}>
                    <div className="empty">暂无数据</div>
                  </td>
                </tr>
              ) : (
                shops.map((row) => (
                  <tr key={row.id}>
                    <td>{row.name}</td>
                    <td className="mono">{row.appid}</td>
                    <td>{row.group_name}</td>
                    <td>
                      <div className="cell-main">
                        <strong>{row.wechat_nickname || "-"}</strong>
                        <span className="subtext">{row.wechat_status || "未同步"}</span>
                      </div>
                    </td>
                    <td>
                      <Pill tone={ctx.statusType(row.status)}>{row.status}</Pill>
                    </td>
                    <td>
                      <Pill tone={row.has_secret ? "success" : "warning"}>
                        {row.has_secret ? "已保存" : "缺失"}
                      </Pill>
                    </td>
                    <td className="mono">{ctx.formatDateTime(row.token_expires_at)}</td>
                    <td>{row.last_quota_remain ?? "-"}</td>
                    <td>
                      <div className="row-actions">
                        <Button
                          size="sm"
                          variant="outline"
                          disabled={!row.has_secret}
                          onClick={() => ctx.verifyShop(row)}
                        >
                          验证
                        </Button>
                        <Button
                          size="sm"
                          variant="outline"
                          disabled={!row.has_secret}
                          onClick={() => ctx.syncShopBasicInfo(row)}
                        >
                          同步资料
                        </Button>
                        <Button
                          size="sm"
                          variant="outline"
                          disabled={!row.has_secret}
                          onClick={() => ctx.checkShopQuota(row)}
                        >
                          查额度
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </section>
  );
}

// src/components/sections/ShopsSection.vue
<script setup lang="ts">
import type { WxXdAppContext } from "../../composables/useWxXdApp";

const props = defineProps<{ ctx: WxXdAppContext }>();
const {
  checkShopQuota,
  createGroup,
  createShop,
  formatDateTime,
  groupForm,
  groups,
  Plus,
  selectedGroupOptions,
  shopForm,
  shops,
  statusType,
  syncShopBasicInfo,
  verifyShop,
} = props.ctx;
</script>

<template>
      <section class="content-stack">
        <div class="panel">
          <div class="panel-title">
            <h2>店铺组</h2>
            <el-tag>{{ groups.length }} 组</el-tag>
          </div>
          <div class="inline-form">
            <el-input v-model="groupForm.name" placeholder="例如：默认铺货组" />
            <el-button type="primary" :icon="Plus" @click="createGroup">新建店铺组</el-button>
          </div>
          <el-table :data="groups" class="dense-table">
            <el-table-column prop="name" label="店铺组" />
            <el-table-column prop="shop_count" label="店铺数" width="100" />
            <el-table-column prop="status" label="状态" width="120">
              <template #default="{ row }">
                <el-tag :type="statusType(row.status)">{{ row.status }}</el-tag>
              </template>
            </el-table-column>
            <el-table-column prop="id" label="ID" min-width="220" />
          </el-table>
        </div>

        <div class="panel">
          <div class="panel-title">
            <h2>接入店铺</h2>
            <p>保存时 app_secret 只发送到 Tauri 后端加密入库，前端不展示、不回填。</p>
          </div>
          <div class="form-grid">
            <el-input v-model="shopForm.name" placeholder="店铺名称" />
            <el-input v-model="shopForm.appid" placeholder="微信小店 appid" />
            <el-input
              v-model="shopForm.app_secret"
              placeholder="微信小店 app_secret"
              type="password"
              show-password
              autocomplete="new-password"
            />
            <el-select v-model="shopForm.group_id" placeholder="选择店铺组">
              <el-option
                v-for="group in selectedGroupOptions"
                :key="group.value"
                :label="group.label"
                :value="group.value"
              />
            </el-select>
            <el-button type="primary" :icon="Plus" @click="createShop">保存店铺</el-button>
          </div>
        </div>

        <div class="panel">
          <div class="panel-title">
            <h2>店铺接入状态</h2>
            <el-tag>{{ shops.length }} 店</el-tag>
          </div>
          <el-table :data="shops" class="dense-table">
            <el-table-column prop="name" label="店铺" min-width="150" />
            <el-table-column prop="appid" label="appid" min-width="170" />
            <el-table-column prop="group_name" label="店铺组" min-width="130" />
            <el-table-column label="微信资料" min-width="170">
              <template #default="{ row }">
                <span>{{ row.wechat_nickname || "-" }}</span>
                <small class="subtext">{{ row.wechat_status || "未同步" }}</small>
              </template>
            </el-table-column>
            <el-table-column prop="status" label="状态" width="130">
              <template #default="{ row }">
                <el-tag :type="statusType(row.status)">{{ row.status }}</el-tag>
              </template>
            </el-table-column>
            <el-table-column label="密钥" width="100">
              <template #default="{ row }">
                <el-tag :type="row.has_secret ? 'success' : 'warning'">
                  {{ row.has_secret ? "已保存" : "缺失" }}
                </el-tag>
              </template>
            </el-table-column>
            <el-table-column label="token 到期" min-width="190">
              <template #default="{ row }">
                {{ formatDateTime(row.token_expires_at) }}
              </template>
            </el-table-column>
            <el-table-column label="接口额度" width="110">
              <template #default="{ row }">
                {{ row.last_quota_remain ?? "-" }}
              </template>
            </el-table-column>
            <el-table-column label="操作" width="250">
              <template #default="{ row }">
                <el-button size="small" :disabled="!row.has_secret" @click="verifyShop(row)">
                  验证
                </el-button>
                <el-button size="small" :disabled="!row.has_secret" @click="syncShopBasicInfo(row)">
                  同步资料
                </el-button>
                <el-button size="small" :disabled="!row.has_secret" @click="checkShopQuota(row)">
                  查额度
                </el-button>
              </template>
            </el-table-column>
          </el-table>
        </div>
      </section>
</template>
